// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjetoBanco.Api.Dados;

#nullable disable

namespace ProjetoBanco.Api.Dados.Migrations
{
    [DbContext(typeof(BancoContexto))]
    partial class BancoContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NUMERO");

                    b.HasKey("Id")
                        .HasName("PK_PB_AGENCIAS");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_PB_AGENCIAS_NUMERO");

                    b.ToTable("PB_AGENCIAS", (string)null);
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGENCIAID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TELEFONE");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)")
                        .HasColumnName("TIPOCLIENTE");

                    b.HasKey("Id")
                        .HasName("PK_PB_CLIENTES");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("IX_PB_CLIENTES_AGENCIAID");

                    b.ToTable("PB_CLIENTES", (string)null);

                    b.HasDiscriminator<string>("TipoCliente").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.Contratacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLIENTEID");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATASOLICITACAO");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MENSAGEM");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRAZOMESES");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUTOID");

                    b.Property<int>("ScoreCalculado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORECALCULADO");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("TaxaJurosMensal")
                        .HasPrecision(10, 4)
                        .HasColumnType("DECIMAL(10,4)")
                        .HasColumnName("TAXAJUROSMENSAL");

                    b.Property<decimal>("ValorParcela")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VALORPARCELA");

                    b.Property<decimal>("ValorSolicitado")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VALORSOLICITADO");

                    b.HasKey("Id")
                        .HasName("PK_PB_CONTRATACOES");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_PB_CONTRATACOES_CLIENTEID");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("IX_PB_CONTRATACOES_PRODUTOID");

                    b.ToTable("PB_CONTRATACOES", (string)null);
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)")
                        .HasColumnName("TIPOPRODUTO");

                    b.HasKey("Id")
                        .HasName("PK_PB_PRODUTOS");

                    b.ToTable("PB_PRODUTOS", (string)null);

                    b.HasDiscriminator<string>("TipoProduto").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.PessoaFisica", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Dominio.Cliente");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATANASCIMENTO");

                    b.Property<decimal>("RendaMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("RENDAMENSAL");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_PB_CLIENTES_CPF")
                        .HasFilter("\"CPF\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("PessoaFisica");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.PessoaJuridica", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Dominio.Cliente");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CNPJ");

                    b.Property<decimal>("FaturamentoMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("FATURAMENTOMENSAL");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RAZAOSOCIAL");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("IX_PB_CLIENTES_CNPJ")
                        .HasFilter("\"CNPJ\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("PessoaJuridica");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.Emprestimo", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Dominio.Produto");

                    b.Property<int>("PrazoMaximoMeses")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRAZOMAXIMOMESES");

                    b.Property<decimal>("ValorMaximo")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VALORMAXIMO");

                    b.Property<decimal>("ValorMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VALORMINIMO");

                    b.HasDiscriminator().HasValue("Emprestimo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Emprestimo pessoal",
                            PrazoMaximoMeses = 48,
                            ValorMaximo = 50000m,
                            ValorMinimo = 500m
                        });
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.MaquinaDeCartao", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Dominio.Produto");

                    b.Property<decimal>("TaxaMdrPadrao")
                        .HasPrecision(10, 4)
                        .HasColumnType("DECIMAL(10,4)")
                        .HasColumnName("TAXAMDRPADRAO");

                    b.HasDiscriminator().HasValue("MaquinaDeCartao");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.ReceberSalario", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Dominio.Produto");

                    b.Property<string>("ConvenioEmpresa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONVENIOEMPRESA");

                    b.HasDiscriminator().HasValue("ReceberSalario");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.Cliente", b =>
                {
                    b.HasOne("ProjetoBanco.Api.Dominio.Agencia", "Agencia")
                        .WithMany("Clientes")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PB_CLIENTES_PB_AGENCIAS_AGENCIAID");

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.Contratacao", b =>
                {
                    b.HasOne("ProjetoBanco.Api.Dominio.Cliente", "Cliente")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PB_CONTRATACOES_PB_CLIENTES_CLIENTEID");

                    b.HasOne("ProjetoBanco.Api.Dominio.Produto", "Produto")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PB_CONTRATACOES_PB_PRODUTOS_PRODUTOID");

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.Agencia", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.Cliente", b =>
                {
                    b.Navigation("Contratacoes");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Dominio.Produto", b =>
                {
                    b.Navigation("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
